repos:
-   repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
          - --remove-unused-variable
          - --ignore-init-module-imports
-   repo: https://github.com/timothycrosley/isort
    rev: 5.12.0  # pick the isort version you'd like to use from https://github.com/timothycrosley/isort/releases
    hooks:
      - id: isort
        args: 
          - "--profile"
          - "black"
-   repo: https://github.com/ambv/black
    rev: 23.9.1
    hooks:
      - id: black
        language_version: python3.10
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: name-tests-test
      - id: debug-statements
