[tool.black]
line-length = 100
target-version = ['py37']

[tool.isort]
known_third_party = [
  "black",
  "click",
  "click_option_group",
  "ethicml",
  "hydra",
  "matplotlib",
  "mypy",
  "numpy",
  "omegaconf",
  "pandas",
  "pylint",
  "pytest",
  "scipy",
  "setuptools",
  "sklearn",
  "torch",
  "tqdm",
  "wandb",
]
known_future_library = []
extra_standard_library = ["dataclasses", "__future__"]
line_length = 88
profile = "black"
force_sort_within_sections = "True"
classes = ["MISSING"]

[tool.poetry]
name = "ranzen"
version = "1.0.0.dev0"
description = "A toolkit facilitating machine-learning experimentation."
authors = ["PAL <info@predictive-analytics-lab.com>"]
license = "Apache License 2.0"
packages = [
  { include = "ranzen" },
]
include=["ranzen/py.typed"]
classifiers=[
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "License :: OSI Approved :: Apache Software License",
  "Operating System :: OS Independent",
  "Typing :: Typed",
]
keywords=["typing", "python"]
repository="https://github.com/predictive-analytics-lab/ranzen"
readme="README.md"

# By default, dependencies across all non-optional groups will be installed when executing poetry install.
# If you only want to install the default, non-grouped dependencies (aka the main group), you can 
# do so with the --only option: ``poetry install --only main``. Equally, you can exclude one or 
# more groups with the --without option: ``poetry install --without torch``.
[tool.poetry.dependencies]
python = ">=3.8.0,<3.11"

[tool.poetry.group.wandb.dependencies]
wandb = ["wandb", "pandas"]

[tool.poetry.group.torch.dependencies]
torch = [
    {version = ">=1.12.1", source = "cu116", markers = "sys_platform == 'linux'"},
    {version = ">=1.12.1", source = "pypi"}
]

[tool.poetry.group.hydra.dependencies]
hydra = ["hydra-core", "neoconfigen"]
hydra-core = { version = "^1.2.0" }
neoconfigen = { version = ">=2.3.3" }

[tool.poetry.group.dev.dependencies]
black = "^22.6"
pytest = "^7.1.2"
isort = "^5.7.0"
darglint = "^1.8.0"
pandas-stubs = ">=1.4.3.220718"

[[tool.poetry.source]]
name = "cu116"
url = "https://download.pytorch.org/whl/cu116"
default = false
secondary = true

[tool.pyright]
exclude = ["**/node_modules", "**/__pycache__", "**/."]
typeCheckingMode = "basic"
pythonVersion = "3.8"
reportUnusedImport = "error"
reportDuplicateImport  = "error"
reportIncompatibleVariableOverride = "error"
reportOverlappingOverload = "error"
reportUntypedNamedTuple = "error"
reportConstantRedefinition = "warning"
reportMissingImports = "error"
reportMissingTypeStubs = "warning"
strictListInference = true
strictSetInference = true
strictParameterNoneValue = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
