---
name: ranzen CI

on:
  pull_request:
    branches:
    - main

jobs:
  format_with_black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install black
      run: |
        python -m pip install --upgrade pip
        pip install 'black<=23'
    - name: Format with black
      run: |
        python -m black --check -l 100 -t py38 -S ranzen/
        python -m black --check -l 100 -t py38 -S tests/

  format_with_isort:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install isort
      run: |
        python -m pip install --upgrade pip
        pip install isort
    - name: Format with isort
      run: |
        isort . --check --diff

  check_docstrings:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install darglint sphinx autodocsumm typing_extensions furo toml
    - name: Check docstrings with darglint
      run: |
        darglint --docstring-style sphinx -v 2 -z long ranzen
    - name: Build with sphinx
      run: |
        sphinx-build -W -b html ./docs ./docs/_build

  run_tests_and_type_checking:
    needs: [format_with_black, format_with_isort, check_docstrings]
    runs-on: ubuntu-latest

    steps:
      # ----------------------------------------------
      #  ----  check-out repo and set-up python ----
      # ----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # ----------------------------------------------
      #  -----  install & configure poetry  -----
      # ----------------------------------------------
      - name: Install Poetry
        uses: snok/install-poetry@v1.2
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      # ----------------------------------------------
      # install dependencies if cache does not exist
      # ----------------------------------------------
      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root

      # ----------------------------------------------
      #  -----  install and run pyright  -----
      # ----------------------------------------------
      - name: Setup node.js (for pyright)
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Install pyright
        run: npm install -g pyright

      - name: Run pyright
        run: |
          poetry run pyright ranzen
          poetry run pyright tests

      # ----------------------------------------------
      #  -----           Run Tests            -----
      # ----------------------------------------------
      - name: Test with pytest
        run: |
          poetry run python -m pytest -vv tests/
