name: Build docs

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    #----------------------------------------------
    #       check-out repo and set-up python
    #----------------------------------------------
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install sphinx
      run: |
        pip install wheel
        pip install sphinx autodocsumm typing_extensions sphinx_rtd_theme

    - name: Build docs
      run: |
        cd docsource
        bash generate_docs.sh

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: ./docs
        github_token: ${{ secrets.GITHUB_TOKEN }}
