---
name: Update and export lock file

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  create-lock-file:
    runs-on: ubuntu-latest

    steps:
      # ----------------------------------------------
      #  ----  check-out repo and set-up python ----
      # ----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      # ----------------------------------------------
      #  -----  install & configure poetry  -----
      # ----------------------------------------------
      - name: Install Poetry
        uses: snok/install-poetry@v1.2
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      # ----------------------------------------------
<<<<<<< HEAD
      #       load cached venv if cache exists
=======
      #  ----  load cached venv if cache exists  ----
>>>>>>> 2735d8ee14e2d4de099847abdaf5059276dd40f5
      # ----------------------------------------------
      - name: Set up Poetry cache for Python dependencies
        id: cached-poetry-dependencies
        # uses: actions/cache@v2
        uses: pat-s/always-upload-cache@v2
        with:
          path: .venv
          key: venvEM2-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

<<<<<<< HEAD
=======
      # ----------------------------------------------
      #  ----  Update dependencies with poetry  ----
      # ----------------------------------------------
>>>>>>> 2735d8ee14e2d4de099847abdaf5059276dd40f5
      - name: Run Poetry update
        run: |
          export PATH="/Users/runner/.local/bin:$PATH"
          rm poetry.lock
          poetry update
          poetry lock --no-update
<<<<<<< HEAD
          poetry export -f requirements.txt --output requirements.txt

=======
          poetry export -f requirements.txt --output requirements.txt -E all

      # ----------------------------------------------
      #  -  Create a PR to update the dependencies -
      # ----------------------------------------------
>>>>>>> 2735d8ee14e2d4de099847abdaf5059276dd40f5
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update poetry.lock and requirements.txt
          title: Update poetry.lock and requirements.txt
          body: Update poetry.lock and requirements.txt
          branch: poetry-lock-and-export
